# Generated by Django 4.2.11 on 2026-02-01 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='brands/')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='news/')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=300)),
                ('text', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='offers/')),
            ],
        ),
        migrations.CreateModel(
            name='Product_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sliders/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('card_img', models.ImageField(upload_to='stores/')),
                ('card_name', models.CharField(max_length=200)),
                ('distance', models.IntegerField()),
                ('location', models.CharField(max_length=300)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
                ('hours', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('marka', models.CharField(max_length=200)),
                ('part_number', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=100)),
                ('series', models.CharField(max_length=100)),
                ('playback_time', models.CharField(max_length=100)),
                ('case_size', models.CharField(max_length=100)),
                ('band_type', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantity', models.IntegerField()),
                ('image', models.ImageField(upload_to='watches/')),
                ('description', models.TextField()),
                ('battery_life', models.CharField(max_length=100)),
                ('connectivity', models.CharField(max_length=100)),
                ('display_type', models.CharField(max_length=100)),
                ('product_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watches', to='core.product_type')),
            ],
        ),
        migrations.CreateModel(
            name='Tv_Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('marka', models.CharField(max_length=200)),
                ('storage', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('color', models.CharField(max_length=100)),
                ('connectivity', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('image', models.ImageField(upload_to='tv_home/')),
                ('description', models.TextField()),
                ('product_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tv_home', to='core.product_type')),
            ],
        ),
        migrations.CreateModel(
            name='Mac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('marka', models.CharField(max_length=200)),
                ('part_number', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('color', models.CharField(max_length=100)),
                ('chip', models.CharField(max_length=100)),
                ('ssd', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('ram', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('image', models.ImageField(upload_to='macs/')),
                ('description', models.TextField()),
                ('product_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='macs', to='core.product_type')),
            ],
        ),
        migrations.CreateModel(
            name='Iphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('marka', models.CharField(max_length=200)),
                ('part_number', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('color', models.CharField(max_length=100)),
                ('series', models.CharField(max_length=100)),
                ('playback_time', models.CharField(max_length=100)),
                ('memory', models.CharField(max_length=100)),
                ('lineup', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('image', models.ImageField(upload_to='iphones/')),
                ('description', models.TextField()),
                ('size', models.CharField(max_length=100)),
                ('sim', models.CharField(max_length=100)),
                ('connectivity', models.CharField(max_length=100)),
                ('camera', models.CharField(max_length=100)),
                ('product_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='iphones', to='core.product_type')),
            ],
        ),
        migrations.CreateModel(
            name='Ipad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('marka', models.CharField(max_length=200)),
                ('part_number', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('color', models.CharField(max_length=100)),
                ('chip', models.CharField(max_length=100)),
                ('cpu', models.CharField(max_length=100)),
                ('memory', models.CharField(max_length=100)),
                ('lineup', models.CharField(max_length=100)),
                ('ram', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('image', models.ImageField(upload_to='ipads/')),
                ('description', models.TextField()),
                ('size', models.CharField(max_length=100)),
                ('sim', models.CharField(max_length=100)),
                ('connectivity', models.CharField(max_length=100)),
                ('display_type', models.CharField(max_length=100)),
                ('product_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ipads', to='core.product_type')),
            ],
        ),
        migrations.CreateModel(
            name='Giftcards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('marka', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantity', models.IntegerField()),
                ('image', models.ImageField(upload_to='accessories/')),
                ('description', models.TextField()),
                ('product_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='giftcards', to='core.product_type')),
            ],
        ),
        migrations.CreateModel(
            name='Airpods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('marka', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('charging_type', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('connectivity', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('image', models.ImageField(upload_to='airpods/')),
                ('description', models.TextField()),
                ('product_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='airpods', to='core.product_type')),
            ],
        ),
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('marka', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('color', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('image', models.ImageField(upload_to='accessories/')),
                ('description', models.TextField()),
                ('product_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='core.product_type')),
            ],
        ),
    ]
