# Generated by Django 5.0.2 on 2026-02-06 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='map_embed',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
